# Manipulating NumPy Arrays

In [1]:
import numpy as np

## Looping Through Arrays

In [2]:
arrA = np.array([(11, 12, 13), (14, 15, 16)])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [3]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [4]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The difference between the two loops is that looping through the first dimension it multipled the values yet stayed within the brackets but when looping the second dimension the values display in one single column

In [5]:
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


 ## Joining and Stacking Arrays

In [6]:
joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [7]:
joined_array_2 = np.concatenate((arrA, arrA), axis = 1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [8]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [9]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2)
# The error message I get here is a ValueError('all input arrays must have the same shape')

ValueError: all input arrays must have the same shape

In [10]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [11]:
another_2 = np.concatenate((joined_array_1, arrA), axis = 1)
print(another_2)
# Arrays are joined on an axis but but these two arrays are of different sizes making them incompatable to be joined

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [12]:
row_stack = np.hstack((arrA, arrA))
print(row_stack)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


The function hstack is stacking the values along rows, like connecting two things horizontally

In [13]:
vert_stack = np.vstack((arrA, arrA))
print(vert_stack)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


The function vstack is stacking the values along columns, like connecting two things veritcally

In [14]:
depth_stack = np.dstack((arrA, arrA))
print(depth_stack)

[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


The function dstack is stacking the values where a third axis is created to form a 3D array

## Splitting Arrays

In [15]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)
# The result of the split was 2 arrays that are also 2D arrays

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [ ]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)
# The result of the split was 3 arrays that are also 3D arrays

## Searching and Replacing Array Values

In [16]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [17]:
arrB = np.array([(7,6),(13,5),(7,3)])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [18]:
print(arrB)
z = arrB < 7
arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [19]:
y = arrB >= 7
arrD = arrB[y]
print(arrD)

[ 7 13  7]
