# Manipulating NumPy Arrays

In [1]:
import numpy as np

## Looping Through Arrays

In [2]:
arrA = ([(11, 12, 13), (14, 15, 16)])
print(arrA)

[(11, 12, 13), (14, 15, 16)]


In [3]:
for x in arrA:
    print(x * 2)

(11, 12, 13, 11, 12, 13)
(14, 15, 16, 14, 15, 16)


In [8]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The difference between the two loops is when looping through the first dimension and multiplying by 2 the output is the tuple repeated twice, when looping through the second dimension and multiplying by 2 the output is the individual numbers multiplied by 2 in a single column.

In [9]:
for x in arrA:
    for y in x:
        loop_result = y * 2
        print(loop_result)

22
24
26
28
30
32


 ## Joining and Stacking Arrays

In [24]:
joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [25]:
joined_array_2 = np.concatenate((arrA, arrA), axis = 1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [27]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [28]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2)

ValueError: all input arrays must have the same shape

In [30]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [31]:
another_2 = np.concatenate((joined_array_1, arrA), axis = 1)
print(another_2)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [32]:
row_stack = np.hstack((arrA, arrA))
print(row_stack)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [35]:
vert_stack = np.vstack((arrA, arrA))
print(vert_stack)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [34]:
depth_stack = np.dstack((arrA, arrA))
print(depth_stack)

[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]
