# Getting Started with NumPy

In [1]:
import numpy as np

## Array Basics

In [2]:
fruits = ['apple', 'banana', 'cherry', 'date']

In [4]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [5]:
arr_1.dtype

dtype('<U6')

In [6]:
# The data type returned in U6 which means Unicode string with a maximum of 6 characters within a single value = U6

In [12]:
arr_2 = np.array([(10,11,12),(13,14,15)])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [16]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [19]:
# When using .T function to transpose my dimensions it alters the values by displaying 2 columns with 3 rows instead of 2 rows with 3 columns

In [20]:
arr_3 = np.array([(1,3,5),(2,4,6)])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [27]:
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])
print(arr_4)

[5 4]


In [31]:
arr_5 = np.array([[[1, 1], [1, 1]], [[1, 1], [1, 1]]])
arr_5

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])